import { ClerkProvider, RedirectToSignIn } from '@clerk/nextjs';
import { PT_Sans } from "next/font/google";
import { ReactNode } from 'react';
import { Metadata } from 'next';
import '@/styles/globals.css';

const inter = PT_Sans({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SaaS Invoice",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <link rel="icon" href="../public/logo.ico" type="image/x-icon" />
        </head>
        <body className={inter.className}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
